global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "auth-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["auth-api:4500"]
